name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Init Terraform
        run: cd terraform && terraform init -backend=false

      - name: Validate Terraform
        run: cd terraform && terraform validate

  lint:
    name: Lint Python Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt flake8

      - name: Run flake8
        run: flake8 scripts

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint   # ensures lint runs before tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run pytest
        run: pytest -q

  # Optional stage for future improvements
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'   # only run on push, not PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bandit (Python security linter)
        run: pip install bandit && bandit -r scripts || true
